package com.example.feature.material.presentation


data class SlideMenuItem(
    var id: String = SlideMenuItemId.QR_MATERIAL_RECEIPT_WITH_PACKAGE,
    var name: String = ""
)

object SlideMenuItemId {
    const val QR_MATERIAL_RECEIPT_WITH_PACKAGE = "QR_MATERIAL_RECEIPT_WITH_PACKAGE"
    const val QR_QC_MATERIAL = "QR_QC_MATERIAL"
    const val QR_QC_SKIN_GRADE = "QR_QC_SKIN_GRADE"
    const val QR_LOADING_MATERIAL_INTO_RACK = "QR_LOADING_MATERIAL_INTO_RACK"
    const val QR_FIXING_RECEIPT_QUANTITY = "QR_FIXING_RECEIPT_QUANTITY"
    const val QR_PICKING_MATERIAL_WITH_PACKAGE = "QR_PICKING_MATERIAL_WITH_PACKAGE"

    const val QR_PICKING_MATERIAL_BY_DELIVERY_ORDER = "QR_PICKING_MATERIAL_BY_DELIVERY_ORDER"
    const val QR_MATERIAL_RECEIPT_BY_OTHER_CASE = "QR_MATERIAL_RECEIPT_BY_OTHER_CASE"
    const val QR_MATERIAL_CHECKING = "QR_MATERIAL_CHECKING"
    const val SEARCHING_MATERIAL = "SEARCHING_MATERIAL"

    const val NOTHING = "NOTHING"
    const val HOME = "HOME"
    const val SIGN_OUT = "SIGN_OUT"
    const val QR_MATERIAL_RECEIPT_WITH_PACKAGE_LIST = "QR_MATERIAL_RECEIPT_WITH_PACKAGE_LIST"

}